[build]
target = "x86_64-unknown-none"
rustflags = ["--cfg", "fw=\"1100\"", "--cfg", "method=\"direct\"", "-Z", "unstable-options", "-C", "panic=immediate-abort"]

[unstable]
build-std = ["alloc", "core"]
